services:
  - type: web
    name: LaravelAPI
    env: local
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y curl zip unzip git
      curl -sS https://getcomposer.org/installer | php
      php composer.phar install
      php artisan key:generate
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:XBut1hUuYuwDE9uWOXA9z81KcFJEX5nxxnnxtA+rCQw= # Bạn nên tạo key bằng lệnh `php artisan key:generate` hoặc copy từ `.env`
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        value: https://your-app-url.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: sql108.infinityfree.com
      - key: DB_PORT
        value: '3306'
      - key: DB_DATABASE
        value: if0_37728845_demobanhang
      - key: DB_USERNAME
        value: if0_37728845
      - key: DB_PASSWORD
        value: ww5ZVNLZpZJiqs
